[build]
  command = "npm run build"
  publish = "out"

/** @type {import('next').NextConfig} */
const nextConfig = {
  eslint: { ignoreDuringBuilds: true },
  images: { unoptimized: true },
  output: 'export',
  trailingSlash: true,
  distDir: 'out'
};
export default nextConfig;/** @type {import('next').NextConfig} */
const nextConfig = {
  eslint: { ignoreDuringBuilds: true },
  images: { unoptimized: true },
  output: 'export',
  trailingSlash: true,
  distDir: 'out'
};
export default nextConfig;[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200
